import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
<br /><br />
      2023 benefits guide Focused on your well-being.<br/>
      At Best Buy, we want to help you live a happy, healthy and productive life—at work, and at home with those who matter most. That&apos;s why we offer a range of benefits that support your overall well-being: physical, mental, financial and work-life balance.<br/><br/>
      </main>
    </>
  )
}
